name: check that code works
on: [push]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "running tests on ${{ runner.os }}"
      - run: echo "Working directory is ${{ github.workspace }}"
      - run: echo "Branch is ${{ github.ref }}"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pixi
        uses: prefix-dev/setup-pixi@v0.9.3
        with:
          pixi-version: v0.62.2 # good to pin this since pixi is not 1.0 yet!

      - run: pixi run pytest

